version: "2"

linters:
  settings:
    staticcheck:
      dot-import-whitelist:
        - "maragu.dev/glue/http"
        - "maragu.dev/gomponents"
        - "maragu.dev/gomponents/components"
        - "maragu.dev/gomponents/html"
